### PR TITLE
test(recovery): qualify transition interruption recovery

### PR DESCRIPTION
**Pull request by Ganesh-403**
## Problem

FAI-519 had no qualification proving that an interrupted forward transition can be classified and resumed from the merged PostgreSQL recovery ledger, or that a running target and stale owners fail closed.

## Root cause

The transition runner and FAI-1001 ledger had independent durability and fencing coverage, but no process-level interruption matrix joined them across migration, staging, activation, restart, validation, evidence publication, and cleanup boundaries.

## Solution

- Add `task qualify:ubdr:migration-interruption` with race detection and PostgreSQL conformance enabled.
- Kill disposable runner processes with `SIGKILL` at six forward-effect boundaries.
- Reclaim the same durable recovery occurrence under a new fence and resume with a newly fenced transition operation after the interrupted operation is conservatively finalized as indeterminate.
- Read migration, immutable generation, active generation, and runtime identity from their existing owners so replay does not duplicate completed mutations.
- Cover failed preflight, an indeterminate post-effect outcome, a running target that retains exclusive ownership, stale transition and ledger fences, evidence-publication retry, and abandoned-run cleanup.
- Persist a scenario matrix, per-scenario checkpoints/reports, and a PostgreSQL ledger export.

## Tests added/updated

- Added the nine-scenario FAI-519 PostgreSQL qualification matrix.
- Extended the host-install qualification bridge build tag for the FAI-519 lane.
- Documented the qualification command, evidence, and scope limits.

## Verification performed

- `task qualify:ubdr:migration-interruption`
- Focused transition runner, release PostgreSQL, recovery, recovery PostgreSQL, host-install, and recovery-ledger PostgreSQL tests
- `git diff --check`
- Full `task ci`

The first full CI attempt hit the unchanged MinIO free-drive threshold because disposable local Docker/build caches exhausted the runner disk. After pruning those disposable caches, the unchanged MinIO contract passed independently and the complete `task ci` rerun passed.

## Remaining limitations

This qualification does not implement provider restoration, replacement-host rebuild, rollback, or RPO/RTO evaluation.

Linear: FAI-519

### CODE REVIEW

**Comment by Ganesh-403** [comment]
Implemented the five requested FAI-519 evidence corrections in `e29cc8473fcb34b96e3ee4ad65bc95e82ed9533f`:

- Completion evidence now stores interrupted, resumed, and completed operation IDs separately. Completion is bound to the resumed `config.OperationID`, with a regression assertion that interrupted and completed identities cannot be mixed.
- Added failpoints that fire only after PostgreSQL `RecordPhase` succeeds. The qualification proves the durable phase exists before SIGKILL and that its external mutation is not duplicated after restart, while retaining the existing before-effect cases.
- Each scenario now derives exactly one of `prior-valid`, `candidate-valid`, or `recoverable-pending` from persisted pre-resume database, ledger, phase, effect, runtime, and generation state. Zero or multiple matches fail the qualification.
- Running-target rejection now executes through the supported transition path against a genuinely running target and asserts rejection before the first effect; no fabricated transition failure is inserted.
- PostgreSQL credentials are passed to child processes through the environment, outside the evidence tree. The qualification scans all published evidence and rejects DSN/password material.

Validation passed locally:

- `go test -tags='fai518qualification fai519qualification' ./internal/recoveryset/postgres -run 'TestFAI519' -count=1`
- `task qualify:ubdr:migration-interruption` (race enabled; 14 scenarios)
- `go test ./internal/release/transitionrunner ./internal/release/postgres ./internal/refresh/postgres ./internal/recoveryset/postgres ./internal/app/cli/hostinstall -count=1`
- `git diff --check`
- full `task ci`

Evidence: `.tmp/qualification/ubdr/migration-interruption`.

Hosted checks have restarted for the new head and are currently running.
